### ISSUE TITLE
Cant connect to Niagara N4.8

### ISSUE THREAD

**Issue by judders** [IOT-DSA/dslink-dart-dgapi#14]
Cant connect to Niagara 4.8 running dglux5.service.

**Comment by ilyatsarev** [comment]
Hi @judders, do you see any errors?

**Comment by judders** [comment]
Hi @ilyatsarev , Thanks for some help.

Trying to connect from DSA to http://192.168.1.31/dglux5. 

Dsa logs...
[2020-09-10 00:34:08.295563] [WARNING][DSA] Failed to fetch http://192.168.1.31/dglux5/dgconfig.json.
[2020-09-10 00:34:08.295569] [WARNING][DSA] SocketException: Connection failed (OS Error: Too many open files, errno = 24), address = 192.168.0.31, port = 80

Have verified /dglux5/dgconfig.json exists on Niagara 4.8 installation with dglux5 service running.
Have verified port 80 for Niagara.

Wireshark on Niagara shows invalid password. But the password is correct? 

Any Ideas would be appreciated. Cant find any guides.

**Comment by ilyatsarev** [comment]
@rinick, have you seen an error like this before? Any recommendations?
I'd say something is not right with the permissions for this user on the Niagara side.

**Comment by rinick** [comment]
if DGLux module is installed, then it might be the auth mode.
right now it requires niagara to allow basic auth.
If this server is accessible from internet, you might also need to disable http and only allow https. otherwise basic auth is not safe.

**Comment by judders** [comment]
Thanks @ilyatsarev and @rinick .

Issue is sorted. Knew I was on the right track with Auth mode. I couldn't see settings in Niagara. But found I had to add the module, and change the user for basic auth.

Thanks Again!
